# docker build --tag ifesunmola/playground-client . --file Dockerfile-client
# docker push ifesunmola/playground-client:latest
FROM node:22.17.0-alpine as builder

WORKDIR /app
COPY ./web-client/package*.json ./
RUN npm install
COPY ./web-client/ ./
RUN npm run build

# Final
FROM nginx:1.25.2-alpine
COPY --from=builder /app/dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
